replicaCount: 1

image:
  repository: filesys-mcp-server
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 9090

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi
    ephemeral-storage: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}

filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 100Mi
  serviceAccount:
    name: filebrowser-sa
    create: true

config:
  mcpProxy:
    baseURL: "http://mcp-filesys:9090"
    addr: ":9090"
    name: "MCP Proxy"
    version: "1.0.0"
    type: "sse"
    options:
      panicIfInvalid: false
      logEnabled: true
      authTokens:
        - "DefaultTokens"
  mcpServers:
    filesystem:
      command: "mcp-filesystem-server"
      args:
        - "/data"

serviceAccount:
  name: mcp-filesys-sa
  create: true

mcpServer:
  # timeout: "30s"  # Uncomment and adjust for long-running file operations (e.g., "5m", "10m")