apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluator
metadata:
  name: kyc-llm-metrics-evaluator-v4
  labels:
    app: kyc-demo-ark-v4-tools
    category: llm-metrics
    type: performance-monitoring
spec:
  description: "LLM performance metrics evaluator for KYC assessment queries"
  address:
    value: "http://ark-evaluator.default.svc.cluster.local:8000/evaluate-metrics"
  parameters:
    # Token usage thresholds
    - name: maxTokens
      value: "25000"  # Allow for comprehensive KYC analysis with tools and GPT-4
    - name: tokenEfficiencyThreshold
      value: "0.3"    # Good completion/prompt ratio

    # Cost management
    - name: maxCostPerQuery
      value: "1.00"   # Higher budget for complex KYC with tools and GPT-4
    - name: costEfficiencyThreshold
      value: "0.7"

    # Performance requirements
    - name: maxDuration
      value: "120.0"  # 2 minutes max for KYC assessment
    - name: minTokensPerSecond
      value: "5.0"    # Reasonable throughput for complex workflow

    # Quality standards
    - name: minResponseLength
      value: "10"     # Minimal response length requirement
    - name: maxResponseLength
      value: "8000"   # Prevent overly verbose responses
    - name: responseCompletenessThreshold
      value: "0.8"    # High completeness for financial analysis

    # Scoring weights (adjust based on priorities)
    - name: tokenWeight
      value: "0.2"    # Token efficiency
    - name: costWeight
      value: "0.2"    # Cost control critical
    - name: performanceWeight
      value: "0.8"    # Speed matters for UX
    - name: qualityWeight
      value: "0.0"    # Quality measured elsewhere