apiVersion: ark.mckinsey.com/v1alpha1
kind: MCPServer
metadata:
  name: {{ include "mcp-filesys.name" . }}
  labels:
    {{- include "mcp-filesys.labels" . | nindent 4 }}
spec:
  description: "MCP Filesystem Server providing file operations"
  transport: sse
  {{- if .Values.mcpServer.timeout }}
  timeout: {{ .Values.mcpServer.timeout | quote }}
  {{- end }}
  address:
    valueFrom:
      serviceRef:
        name: {{ include "mcp-filesys.name" . }}-server
        port: http
        path: /filesys/sse
