# DevSpace configuration for local ARK services development
version: v2beta1

# Dependencies - include other DevSpace configurations
dependencies:
  ark-cluster-memory:
    path: ./services/ark-cluster-memory
  ark-api:
    path: ./services/ark-api
  ark-dashboard:
    path: ./services/ark-dashboard
  ark:
    path: ./ark
#   ark-mcp:
#     path: ./services/ark-mcp
#     pipeline: dev
#   postgres-memory:
#     path: ./services/postgres-memory

pipelines:
  deploy: |-
    run_dependency_pipelines --all --pipeline=deploy
  dev: |-
    run_dependency_pipelines --all --pipeline=dev


