# DevSpace configuration for local ARK services development
version: v2beta1

# Dependencies - include other DevSpace configurations
dependencies:
  ark-cluster-memory:
    path: ./services/ark-cluster-memory
  ark-api:
    path: ./services/ark-api
  ark-dashboard:
    path: ./services/ark-dashboard
  ark:
    path: ./ark
#   ark-mcp:
#     path: ./services/ark-mcp
#     pipeline: dev
#   postgres-memory:
#     path: ./services/postgres-memory

pipelines:
  deploy: |-
    run_dependency_pipelines --all --pipeline=deploy
    build_images --all
    create_deployments --all
  dev: |-
    run_dependency_pipelines --all --pipeline=dev
    create_deployments --all
    start_dev --all

# Hooks for pre-build setup
hooks:
  - command: ./services/ark-api/ark-api/scripts/ensure-ark-sdk-wheel.sh
    events: ["before:dev", "before:deploy"]


