apiVersion: ark.mckinsey.com/v1alpha1
kind: Query
metadata:
  name: test-final-debug-query
  namespace: default
spec:
  targets:
  - type: agent
    name: test-annotation-pricing-agent
  input: "Calculate 5 * 6 and tell me your model name."