apiVersion: ark.mckinsey.com/v1alpha1
kind: Query
metadata:
  name: test-without-clusterrole-query
  namespace: default
spec:
  targets:
  - type: agent
    name: test-annotation-pricing-agent
  input: "Calculate 12 * 8 and tell me your model name."