apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluation
metadata:
  name: debug-large-timeout-test
  labels:
    app: kyc-demo-ark-v2
    provider: langfuse
    evaluation-type: timeout-test
    use-case: debug-large-payload
spec:
  type: direct
  config:
    input: |
      Analyze this comprehensive KYC assessment for Associated British Foods PLC:
      Company: Associated British Foods PLC (UK Company Number: 00293262)
      CFO: John Bason
      Blacklist Status: 5/10 confidence match for sanctions violations
      Financial Performance: 2% revenue decline, deteriorating margins
      Litigation: 3 ongoing cases including environmental violations
      Regulatory Issues: GDPR compliance concerns, data protection violations
      Risk Factors: High exposure to commodity price volatility, Brexit impact on EU operations
      What is the overall risk assessment and recommended actions?
    output: |
      Based on the comprehensive KYC analysis for Associated British Foods PLC, I assess the following:

      **OVERALL RISK RATING: MEDIUM-HIGH**

      Key Risk Factors:
      1. **Sanctions Exposure**: 5/10 confidence blacklist match indicates potential sanctions violations requiring immediate investigation
      2. **Financial Decline**: 2% revenue decline suggests operational challenges and reduced financial stability
      3. **Active Litigation**: 3 ongoing cases including environmental violations demonstrate regulatory compliance issues
      4. **Data Protection Violations**: GDPR compliance concerns indicate systemic compliance weaknesses

      **Recommended Actions:**
      1. Conduct enhanced due diligence on sanctions exposure immediately
      2. Request detailed financial statements for last 3 quarters
      3. Obtain legal opinions on ongoing litigation exposure
      4. Implement enhanced monitoring for regulatory compliance
      5. Consider elevated transaction limits and increased reporting requirements

      This assessment is based on the provided KYC profile data and current regulatory requirements.
  evaluator:
    name: langfuse-evaluator
    parameters:
      - name: evaluation.context
        value: |
          SOURCE DATA:
          - Company: Associated British Foods PLC (UK Company Number: 00293262)
          - CFO: John Bason
          - Blacklist: 5/10 confidence match for sanctions violations
          - Financial: 2% revenue decline, deteriorating margins
          - Litigation: 3 ongoing cases including environmental violations
          - Regulatory: GDPR compliance concerns, data protection violations
      - name: metrics
        value: "faithfulness"
      - name: threshold
        value: "0.8"