apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluation
metadata:
  name: kyc-ragas-multi-metric
  labels:
    app: kyc-demo-ark-v2
    provider: langfuse
    evaluation-type: ragas-comprehensive
    use-case: kyc-quality-assessment
spec:
  type: direct
  config:
    input: |
      What is the overall risk assessment for Associated British Foods PLC based on the KYC findings?

    output: |
      Based on the KYC findings, Associated British Foods PLC presents a MEDIUM risk level. Key concerns include:
      1. Financial decline with 2% revenue decrease and 12% profit decline
      2. CFO John Bason has a potential blacklist match (5/10 confidence) requiring enhanced due diligence
      3. Ongoing litigation involving 1,700+ plaintiffs and 7 fatalities in Malawi
      The combination of financial performance issues, regulatory concerns, and litigation exposure warrants enhanced monitoring and due diligence procedures.

  evaluator:
    name: langfuse-evaluator
    parameters:
      - name: evaluation.context
        value: |
          KYC FINDINGS:
          - Company: Associated British Foods PLC, UK-based multinational
          - Financial: 2% revenue decrease, 12% profit decline, increased net debt
          - Blacklist: CFO John Bason similarity to "John Donald Basin" (5/10 confidence)
          - Sanctions: All controllers cleared
          - Litigation: 1,700+ Malawian citizens lawsuit, 7 fatalities involved
          - Operations: 56 countries, 138,000 employees
          - Ownership: Wittington Investments Limited holds 56.1% stake

      - name: evaluation.context_source
        value: "kyc_comprehensive_findings"

      # Use multiple RAGAS metrics for comprehensive assessment
      - name: metrics
        value: "faithfulness,answer_correctness,answer_relevancy"

      # Standard threshold for multi-metric assessment
      - name: threshold
        value: "0.8"