apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluation
metadata:
  name: kyc-faithfulness-evaluation
  labels:
    app: kyc-demo-ark-v2
    provider: langfuse
    evaluation-type: faithfulness
    use-case: kyc-risk-assessment
spec:
  type: query
  config:
    queryRef:
      name: kyc-assessment-query-with-data-events
      namespace: default
      # Evaluate the complete team response for faithfulness
  evaluator:
    name: kyc-faithfulness-evaluator
    parameters:
      # Override evaluation focus for faithfulness
      - name: evaluation_focus
        value: "faithfulness_to_source"

      # Detailed assessment criteria for KYC faithfulness
      - name: assessment_criteria
        value: |
          Evaluate the KYC risk assessment response for faithfulness to the provided data:

          1. FACTUAL ACCURACY:
             - Are all financial figures (2% revenue decrease, 12% profit decline) correctly cited?
             - Is the ownership structure (56.1% by Wittington) accurately stated?
             - Are employee counts (138,000) and geography (56 countries) correct?

          2. RISK FINDING FAITHFULNESS:
             - Is the John Bason blacklist match (5/10 confidence) accurately described?
             - Is the Malawi litigation (1,700+ plaintiffs, 7 fatalities) correctly referenced?
             - Are sanctions screening results accurately reported (all clear)?

          3. NO HALLUCINATION:
             - Does the assessment avoid adding risks not mentioned in the input?
             - Are all statements traceable to the provided KYC data?
             - Does it avoid speculation beyond the given facts?

          4. CONTEXT USAGE:
             - Does the response properly use the adverse media information?
             - Are the financial performance indicators correctly interpreted?
             - Is the relationship purpose accurately reflected?

          Score based on how faithfully the response adheres to ONLY the provided KYC data.

      # Context for RAGAS evaluation
      - name: context
        value: |
          The response must be evaluated against the original KYC profile data provided,
          including company details, risk findings, key controllers, and adverse media.
          Any information not present in the original input should be considered a faithfulness violation.

      # Increase weight for faithfulness metric
      - name: metric_weights
        value: "faithfulness:0.5,relevance:0.3,correctness:0.2"

  # Timeout for complex evaluation
  timeout: 5m

  # TTL for evaluation results
  ttl: 720h