apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluation
metadata:
  name: kyc-query-context-metrics-evaluation
  labels:
    app: kyc-demo-ark-v3
    provider: llm
    evaluation-type: query-context-metrics
    use-case: kyc-risk-assessment
spec:
  type: query
  config:
    queryRef:
      name: kyc-context-enhanced-query
      # Optionally specify which response to evaluate when query has multiple targets
      # responseTarget: risk-officer-rag-kyc-v3

  evaluator:
    name: kyc-context-metrics-evaluator
    parameters:
    - name: context
      value: |
        Customer Profile: Associated British Foods PLC
        Industry: Food processing and retail, Founded: 1935
        Key Markets: UK, Europe, Asia, Africa
        Primary Business Segments: Grocery, Sugar, Agriculture, Retail

        Risk Assessment Data:
        Credit Rating: A-, Regulatory Compliance: Excellent
        Market Position: Leading multinational
        Financial Stability: Strong cash flow and balance sheet

        Controller Information:
        Chairman: Michael McLintock (pending nationality verification)
        CEO: George Weston (pending residency documentation)
        Independent Directors: Multiple with diverse backgrounds
        Screening Status: All cleared with 10/10 confidence scores
    - name: scope
      value: "relevance,accuracy,context_precision,context_recall"
    - name: min-score
      value: "0.6"
