apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluation
metadata:
  name: kyc-hallucination-simple
  labels:
    app: kyc-demo-ark-v2
    provider: langfuse
    evaluation-type: hallucination-detection
    use-case: kyc-risk-assessment
spec:
  type: direct
  config:
    input: |
      Based on the KYC data provided, what is the CFO's blacklist confidence score?

    output: |
      The CFO John Bason has a blacklist confidence score of 5/10 for similarity to "John Donald Basin".

  evaluator:
    name: langfuse-evaluator
    parameters:
      - name: evaluation.context
        value: |
          KYC DATA:
          - CFO: John Bason
          - Blacklist screening: John Bason has similarity to "John Donald Basin" on blacklist (confidence score: 5/10)
          - All other controllers cleared sanctions screening
          - Company: Associated British Foods PLC

      - name: evaluation.context_source
        value: "kyc_blacklist_data"

      # Focus purely on faithfulness to detect hallucinations
      - name: metrics
        value: "faithfulness"

      # High threshold - should pass if no hallucinations
      - name: threshold
        value: "0.9"