apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluator
metadata:
  name: kyc-faithfulness-evaluator
  labels:
    app: kyc-demo-ark-v2
    provider: langfuse
    evaluation-type: faithfulness
    use-case: kyc-risk-assessment
spec:
  description: "Langfuse-based faithfulness evaluation for KYC risk assessment responses"
  address:
    value: "http://ark-evaluator.default.svc.cluster.local:8000/evaluate"
  parameters:
    # Provider configuration
    - name: provider
      value: langfuse

    # Langfuse connection from ConfigMap
    - name: langfuse.host
      valueFrom:
        configMapKeyRef:
          name: langfuse-kyc-config
          key: host

    - name: langfuse.project
      valueFrom:
        configMapKeyRef:
          name: langfuse-kyc-config
          key: project

    # Langfuse credentials from Secret
    - name: langfuse.public_key
      valueFrom:
        secretKeyRef:
          name: langfuse-kyc-secrets
          key: public_key

    - name: langfuse.secret_key
      valueFrom:
        secretKeyRef:
          name: langfuse-kyc-secrets
          key: secret_key

    # Azure OpenAI configuration (using the same as your main setup)
    - name: langfuse.azure_endpoint
      value: "https://lxo.openai.azure.com/"

    - name: langfuse.azure_deployment
      value: "gpt-4.1-mini"

    - name: langfuse.model_version
      value: "2024-12-01-preview"

    - name: langfuse.azure_api_key
      valueFrom:
        secretKeyRef:
          name: azure-openai-secret  # Assuming this exists from your setup
          key: token

    # Embedding configuration for semantic similarity
    - name: langfuse.azure_embedding_deployment
      value: "text-embedding-ada-002"

    - name: langfuse.azure_embedding_model
      value: "text-embedding-ada-002"

    # Evaluation metrics focused on faithfulness
    - name: metrics
      value: "faithfulness,relevance,correctness"

    # Higher threshold for risk assessment accuracy
    - name: threshold
      value: "0.85"

    # Custom evaluation context for KYC
    - name: evaluation_context
      value: |
        This is a KYC risk assessment evaluation. Check that:
        1. All risk findings are directly based on the provided KYC data
        2. Financial figures match the input data exactly
        3. No additional risks are invented beyond what's in the source
        4. The assessment uses only the facts provided about the company