apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.name }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.app.image.pullPolicy }}"
        ports:
        - containerPort: 7184
        env:
        - name: ARK_A2A_LISTEN_PORT
          value: "80"
        - name: ARK_A2A_LISTEN_HOST
          value: "127.0.0.1.nip.io"
        - name: ARK_A2A_LISTEN_PROTOCOL
          value: "http"
        - name: ARK_A2A_LISTEN_PATH
          value: "/a2a"
        - name: A2A_DEFAULT_TIMEOUT
          value: "{{ .Values.app.defaultTimeout }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}