apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluation
metadata:
  name: kyc-rag-context-evaluation
  labels:
    app: kyc-demo-ollama-rag
    provider: llm
    evaluation-type: query-context-metrics
    use-case: kyc-risk-assessment
spec:
  type: query
  config:
    queryRef:
      name: kyc-context-enhanced-query-ollama
      # Optionally specify which response to evaluate when query has multiple targets
      # responseTarget: risk-officer-rag-kyc-ollama

  evaluator:
    name: kyc-context-metrics-evaluator-v4
    parameters:
    - name: context
      value: |
        # Retrieved RAG Chunks from KYC Customer Profile

        ## CHUNK 1: Adverse Media Screening & Regulatory Compliance
        Comprehensive adverse media screening has been conducted across all key personnel with no significant negative findings identified.

        Risk Assessment Considerations:
        - Geographic Diversification: Operations span multiple jurisdictions requiring compliance with various regulatory frameworks
        - Leadership Quality: Experienced board with independent directors and clear governance structure
        - Screening Results: Clean screening results across all personnel with high confidence scores
        - Documentation: Some nationality and residency information pending completion for certain individuals

        Regulatory Compliance:
        The entity demonstrates strong compliance posture with:
        - Complete blacklist screening for all key personnel
        - Proper identification of key controllers and beneficial owners
        - Transparent ownership structure documentation
        - Regular adverse media monitoring

        ## CHUNK 2: Business Activities
        The entity appears to be a legitimate business operation with proper corporate governance structures, independent board oversight, and comprehensive compliance procedures in place.

        ## CHUNK 3: Initial Profile & Key Personnel Screening
        KYC Customer Profile Data - Initial Profile:
        Based on the customer profile, this is a UK-based entity with multiple key controllers and directors from various nationalities including British, Australian, Turkish, French, and Canadian backgrounds.

        Internal Blacklist Screening Results:
        - Graham Denis Allan: Chair, Independent Director, British/Australian, England, Not on blacklist, 10/10 confidence
        - Heather Victoria Rabbatts: Senior Independent Director, British, UK, Not on blacklist, 10/10 confidence

        ## CHUNK 4: Key Controllers Analysis & Ownership Structure
        The entity has a diverse international board composition with representatives from multiple jurisdictions. All key controllers have been verified and cleared through screening processes. The leadership structure includes:
        - Chairman and CEO roles clearly defined
        - Multiple independent directors providing governance oversight
        - International experience across UK, Australia, Canada, Turkey, and France

        Ownership Structure:
        The ownership structure involves multiple entities and individuals with varying levels of control and influence. All controllers have been properly identified and screened.

        ## CHUNK 5: Additional Key Personnel (Critical Findings)
        - Anne Louise Murphy: Independent Director, British, UK, Not on blacklist, 10/10 confidence
        - Michael McLintock: Chairman, Nationality/Residency not available, Not on blacklist, 10/10 confidence
        - Muhammad Anwar: Chief Agentic Evaluation Officer, UK residency, **ON BLACKLIST**, 7/10 confidence
        - George Weston: Chief Executive Officer, Nationality/Residency not available, Not on blacklist, 10/10 confidence

    - name: scope
      value: "relevance,accuracy,context_precision,context_recall"
    - name: min-score
      value: "0.6"
    - name: evaluator-role
      value: |
        You are evaluating a KYC risk assessment based on the provided context chunks retrieved by the RAG system.

        MANDATORY OUTPUT FORMAT - You MUST include ALL these lines:
        SCORE: [number between 0 and 1]
        PASSED: [true or false]
        REASONING: [your evaluation explanation]
        CRITERIA_SCORES: relevance=0.95, accuracy=0.9, context_precision=0.9, context_recall=0.75

        For CRITERIA_SCORES, evaluate each metric from 0 to 1:
        - relevance: How well the response addresses the KYC risk assessment query
        - accuracy: How correct the information is based on the retrieved chunks
        - context_precision: How precisely the retrieved context chunks are used
        - context_recall: How well all critical context information (especially blacklist findings) is utilized

        Key evaluation focus:
        - Did the assessment identify Muhammad Anwar's blacklist status from Chunk 5?
        - Were the compliance and regulatory findings from Chunks 1-4 properly analyzed?
        - Was the risk assessment comprehensive and accurate based on the retrieved data?