{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.app.name }}-route
  labels:
    app: {{ .Values.app.name }}
spec:
  parentRefs:
  - name: {{ .Values.httpRoute.gateway.name }}
    namespace: {{ .Values.httpRoute.gateway.namespace }}
  hostnames:
  {{- range .Values.httpRoute.hostnames }}
  - {{ . | quote }}
  {{- end }}
  rules:
  {{- range .Values.httpRoute.rules }}
  - filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        set:
        - name: Origin
          value: "http://n8n.default.127.0.0.1.nip.io"
        - name: X-Forwarded-Proto
          value: "http"
    backendRefs:
    {{- range .backendRefs }}
    - name: {{ .name }}
      port: {{ .port }}
    {{- end }}
  {{- end }}
{{- end }}
