app:
  name: n8n
  image:
    repository: n8n-ark
    tag: latest
    pullPolicy: IfNotPresent

  port: 5678

  env:
    N8N_HOST: n8n.default.127.0.0.1.nip.io
    N8N_PORT: "5678"
    N8N_PROTOCOL: http
    N8N_SECURE_COOKIE: "false"
    N8N_PROXY_HOPS: "1"
    N8N_EDITOR_BASE_URL: http://n8n.default.127.0.0.1.nip.io:8080
    WEBHOOK_URL: http://n8n.default.127.0.0.1.nip.io:8080
    N8N_PUSH_BACKEND: sse
    GENERIC_TIMEZONE: America/New_York
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
    N8N_RUNNERS_ENABLED: "true"
    ARK_API_URL: http://ark-api.default.svc.cluster.local

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

storage:
  enabled: true
  size: 1Gi
  storageClass: ""
  accessMode: ReadWriteOnce
  mountPath: /home/node/.n8n

httpRoute:
  enabled: true
  gateway:
    name: localhost-gateway
    namespace: ark-system
  hostnames:
    - n8n.default.127.0.0.1.nip.io
  rules:
    - backendRefs:
        - name: n8n
          port: 5678

service:
  type: ClusterIP
  port: 5678
  targetPort: 5678
