apiVersion: ark.mckinsey.com/v1alpha1
kind: Team
metadata:
  name: kyc-risk-assessment-team-v3
  labels:
    app: kyc-demo-ark-v3
    category: risk-assessment
    workflow: rag-enhanced
    use-case: kyc-risk-assessment
spec:
  description: "RAG-enhanced team for KYC profile analysis with automated report generation and file storage"
  members:
    - name: planner-agent-kyc-v2
      type: agent
    - name: risk-officer-rag-kyc-v3
      type: agent
    - name: file-manager-mcp-kyc-v3
      type: agent
  strategy: sequential