apiVersion: ark.mckinsey.com/v1alpha1
kind: Team
metadata:
  name: kyc-risk-assessment-team
  labels:
    app: kyc-demo-ark
    category: risk-assessment
    workflow: sequential
    use-case: kyc-risk-assessment
spec:
  description: "Sequential team for comprehensive KYC profile analysis, risk assessment, and document generation workflow"
  members:
    - name: planner-agent-kyc
      type: agent
    - name: file-manager-kyc
      type: agent
    - name: risk-officer-kyc
      type: agent
    - name: critic-kyc
      type: agent
  strategy: sequential
  maxTurns: 4