apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluator
metadata:
  name: kyc-response-evaluator
  labels:
    app: kyc-demo-ark-v2
    category: response-evaluation
    use-case: kyc-risk-assessment
spec:
  description: "Evaluates the quality of the final KYC risk assessment response"
  address:
    value: "http://ark-evaluator.default.svc.cluster.local:8000/evaluate"
  parameters:
    - name: model.name
      value: default