apiVersion: ark.mckinsey.com/v1alpha1
kind: Tool
metadata:
  name: rag-search
  namespace: default
  labels:
    app: rag-demo
    type: semantic-search
spec:
  type: http
  description: "Search company knowledge base using semantic similarity (FAISS + embeddings)"
  inputSchema:
    type: object
    properties:
      query:
        type: string
        description: "Natural language query to search for relevant information"
        examples: ["remote work policy", "meeting requirements", "home office stipend"]
      top_k:
        type: integer
        description: "Number of top results to return (default: 3)"
        default: 3
        minimum: 1
        maximum: 10
    required: [query]
  http:
    url: "http://localhost:8000/search"
    method: POST
    headers:
      Content-Type: "application/json"
    body: |
      {
        "query": "{{.query}}",
        "top_k": {{.top_k | default 3}}
      }
    timeout: 30s