apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluator
metadata:
  name: kyc-llm-metrics-evaluator-v4-lenient
  labels:
    app: kyc-demo-ark-v4-tools
    category: llm-metrics
    type: performance-monitoring
spec:
  address:
    value: http://ark-evaluator.default.svc.cluster.local:8000/evaluate-metrics
  description: LLM performance metrics evaluator with lenient response length thresholds for various model types
  parameters:
    # Token limits
    - name: maxTokens
      value: "20000"
    - name: tokenEfficiencyThreshold
      value: "0.3"

    # Cost thresholds
    - name: maxCostPerQuery
      value: "0.50"
    - name: costEfficiencyThreshold
      value: "0.7"

    # Performance thresholds
    - name: maxDuration
      value: "120.0"
    - name: minTokensPerSecond
      value: "5.0"

    # LENIENT Response length thresholds (adjusted for better compatibility)
    - name: minResponseLength
      value: "200"      # Reduced from 1000 to 200 (more lenient)
    - name: maxResponseLength
      value: "25000"    # Increased from 12000 to 25000 (more lenient)

    # Quality thresholds
    - name: responseCompletenessThreshold
      value: "0.8"

    # Evaluation weights
    - name: tokenWeight
      value: "0.2"
    - name: costWeight
      value: "0.3"
    - name: performanceWeight
      value: "0.3"
    - name: qualityWeight
      value: "0.2"