apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluation
metadata:
  name: kyc-event-evaluation
  labels:
    app: kyc-demo-ark-v2
    category: event-evaluation
    use-case: kyc-risk-assessment
spec:
  type: event
  config:
    queryRef:
      name: kyc-assessment-query-with-data-events
      namespace: default
    rules:
      # Rule 1: Tool Usage Check
      - name: "date_tool_called"
        expression: "tools.was_called('get-current-date')"
        description: "Verifies the risk officer called the get-current-date tool"
        weight: 2

      # Rule 2: Team Execution Completeness
      - name: "all_agents_executed"
        expression: "agents.was_executed('default/planner-agent-kyc-v2') and agents.was_executed('default/risk-officer-kyc-v2') and agents.was_executed('default/critic-kyc-v2')"
        description: "Verifies all three KYC agents executed in the sequential workflow"
        weight: 2

      # Rule 3: Reasonable Performance
      - name: "reasonable_execution_time"
        expression: "query.get_execution_time() <= 120.0"
        description: "Ensures KYC assessment completes within 2 minutes"
        weight: 1

      # Bonus: Check team was executed
      - name: "team_executed"
        expression: "teams.was_executed('kyc-risk-assessment-team-v2')"
        description: "Confirms the KYC risk assessment team was properly executed"
        weight: 1

      # Bonus: Verify agent success rate
      - name: "agents_reliable"
        expression: "agent.get_success_rate() >= 0.8"
        description: "Checks that agents have at least 80% success rate"
        weight: 1

  evaluator:
    name: kyc-event-based-evaluator
    parameters:
    - name: query.name
      value: kyc-assessment-query-with-data-events
    - name: query.namespace
      value: default
    - name: min-score
      value: "0.6"