apiVersion: ark.mckinsey.com/v1alpha1
kind: Query
metadata:
  name: kyc-assessment-query-with-data
  labels:
    category: kyc-assessment
    use-case: risk-evaluation
spec:
  input: |
    Analyze the following KYC profile data for Associated British Foods PLC and generate a comprehensive risk assessment memo. The assessment should include financial risk analysis, regulatory compliance evaluation, and operational risk review. Save the final assessment document with proper formatting.

    KYC PROFILE DATA:
    Company: Associated British Foods PLC (UK Company Number: 00293262)
    Address: Weston Centre, 10 Grosvenor Street, London W1K 4QY, United Kingdom
    Industry: Diversified international food, ingredients, and retail group
    Employees: 138,000 worldwide
    Global Operations: 56 countries with manufacturing plants in Europe, Southern Africa, the Americas, Asia, and Australia

    KEY RISK FINDINGS:
    1. BLACKLIST SCREENING: One potential match found - John Bason (CFO) has similarity to "John Donald Basin" on blacklist due to cyberattack links (confidence score: 5/10)
    2. SANCTIONS SCREENING: All key controllers cleared - no matches found
    3. LITIGATION: Facing lawsuit from 1,700+ Malawian citizens over flooding deaths (7 fatalities) related to sugar estate flood defenses
    4. OWNERSHIP: Wittington Investments Limited holds 56.1% stake; controlling shareholders have 60.3% combined voting rights
    5. FINANCIAL PERFORMANCE: Recent decline - 2% revenue decrease, 12% adjusted operating profit decline, significant increase in net debt

    KEY CONTROLLERS:
    - Michael McLintock (Chairman)
    - George Weston (CEO) 
    - John Bason (CFO) - flagged for potential blacklist similarity
    - Emma Susan Adamo (Director, Canadian national)
    - Multiple independent directors from UK, Turkey, France, Ireland, Australia

    PURPOSE OF RELATIONSHIP:
    - Corporate Treasury Management Account
    - Foreign Exchange (FX) and Hedging Solutions  
    - Trade Finance Services
    - Global cash flow optimization and currency risk management

    ADVERSE MEDIA:
    - Operational challenges in African sugar businesses
    - Malawi flooding lawsuit with serious allegations
    - Commercial/regulatory challenges with UK bioethanol plant
    - No widespread adverse press on unethical practices
    - Formal anti-corruption policies in place

    Generate a comprehensive risk assessment memo covering all regulatory requirements and provide risk rating recommendations.
  targets:
    - type: team
      name: kyc-risk-assessment-team-v2