{{/*
RBAC - Deploy FIRST to ensure permissions are available
Creates ServiceAccount and necessary RoleBindings for ARK resources
*/}}
{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "{{ .Values.project.name }}.serviceAccountName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "{{ .Values.project.name }}.labels" . | nindent 4 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "{{ .Values.project.name }}.fullname" . }}-default-permissions
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-19"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "{{ .Values.project.name }}.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: agent-viewer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "{{ .Values.project.name }}.fullname" . }}-default-team-permissions
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-19"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "{{ .Values.project.name }}.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: team-viewer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "{{ .Values.project.name }}.fullname" . }}-default-model-permissions
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-19"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "{{ .Values.project.name }}.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: model-viewer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "{{ .Values.project.name }}.fullname" . }}-secret-reader
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-19"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "{{ .Values.project.name }}.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "{{ .Values.project.name }}.fullname" . }}-default-secret-permissions
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-19"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "{{ .Values.project.name }}.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "{{ .Values.project.name }}.fullname" . }}-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "{{ .Values.project.name }}.fullname" . }}-agent-viewer
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-19"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "{{ .Values.project.name }}.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "{{ .Values.project.name }}.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: agent-viewer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "{{ .Values.project.name }}.fullname" . }}-team-viewer
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-19"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "{{ .Values.project.name }}.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "{{ .Values.project.name }}.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: team-viewer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "{{ .Values.project.name }}.fullname" . }}-query-admin
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-19"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "{{ .Values.project.name }}.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "{{ .Values.project.name }}.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: query-admin-role
  apiGroup: rbac.authorization.k8s.io