apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pgvector/
  - retrieval-service/deployment/
  - tools/retrieve-chunks.yaml
  - tools/search-by-metadata.yaml
  - tools/get-document-stats.yaml
  - agents/rag-agent.yaml
  - queries/rag-query.yaml

