apiVersion: ark.mckinsey.com/v1alpha1
kind: Evaluation
metadata:
  name: kyc-single-metric-test
  labels:
    app: kyc-demo-ark-v2
    provider: langfuse
    evaluation-type: ragas-single-test
    use-case: metric-count-test
spec:
  type: direct
  config:
    input: |
      What is the risk level for Associated British Foods?

    output: |
      MEDIUM risk level due to financial decline and CFO blacklist match.

  evaluator:
    name: langfuse-evaluator
    parameters:
      - name: evaluation.context
        value: |
          KYC DATA:
          - Financial: 2% revenue decrease, 12% profit decline
          - CFO: John Bason has blacklist match (5/10 confidence)

      - name: evaluation.context_source
        value: "kyc_data"

      # Single metric only
      - name: metrics
        value: "faithfulness"

      - name: threshold
        value: "0.8"