{{- if .Values.otelEnvironmentVariableSecrets.enabled }}
{{- $endpoint := printf "http://%s.%s.svc.cluster.local:%v/api/public/otel" .Values.service.name .Values.namespace (.Values.service.port | int) }}
{{- $publicKey := .Values.demo.project.publicKey }}
{{- $secretKey := .Values.demo.project.secretKey }}
{{- $authHeader := printf "Authorization=Basic %s" (printf "%s:%s" $publicKey $secretKey | b64enc) }}
{{- range .Values.otelEnvironmentVariableSecrets.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: otel-environment-variables
  namespace: {{ . }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
stringData:
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ $endpoint }}
  OTEL_EXPORTER_OTLP_HEADERS: {{ $authHeader }}
{{- end }}
{{- end }}
