# DevSpace configuration for ark-api-a2a service
version: v2beta1

images:
  ark-api-a2a:
    image: ark-api-a2a
    dockerfile: Dockerfile
    context: .

dependencies:
  ark-sdk:
    path: ../../lib/ark-sdk

pipelines:
  deploy: |-
    run_dependency_pipelines --all --pipeline=deploy
    ./sync-ark-sdk.sh
    build_images --all
    create_deployments --all
  dev: |-
    run_dependency_pipelines --all --pipeline=dev
    ./sync-ark-sdk.sh
    build_images --all
    create_deployments --all
    start_dev --all

deployments:
  ark-api-a2a:
    namespace: default
    helm:
      chart:
        path: ./chart
      values:
        app:
          image:
            repository: ${runtime.images.ark-api-a2a.image}
            tag: ${runtime.images.ark-api-a2a.tag}
          # Override resources for local development
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
        httpRoute:
          enabled: true
      upgradeArgs: ["--wait", "--timeout=5m"]

dev:
  ark-api-a2a:
    namespace: default
    imageSelector: ark-api-a2a
    devImage: python:3.12-slim
    # Install dependencies and start API server with hot reload
    command:
      [
        "sh",
        "-c",
        "cd /app && pip install uv && uv run uvicorn a2agw.main:app --reload --host 0.0.0.0 --port 7184",
      ]

    # Stream logs instead of terminal
    logs:
      lastLines: 50
    # File synchronization for hot reload
    sync:
      - path: .:/app
        startContainer: true
        disableDownload: true
        uploadExcludeFile: .dockerignore
      - path: ./out:/app/out/
        startContainer: true
        disableDownload: true
        onUpload:
          restartContainer: true
    # Enable SSH for IDE integration
    ssh:
      enabled: true

