replicaCount: 1

image:
  repository: ark-pr-reviewer
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations:
    {}
  name: "ark-pr-reviewer"

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ark-pr-reviewer.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  serviceName: "ark-pr-reviewer"
  logLevel: "INFO"
  githubApiUrl: "https://api.github.com"
  jiraTimeout: 10
  jiraFallbackEnabled: true
  awsRegion: "us-east-1"
  s3Bucket: "ark-pr-review-pr-reviews"
  s3Prefix: "reviews"
  kubernetesNamespace: "ark-pr-review"
  teamName: "pr-review-team"
  reviewTimeout: 300
  apiPort: 8080
  metricsPort: 8000

secrets:
  githubToken: ""
  jiraBaseUrl: ""
  jiraUsername: ""
  jiraApiToken: ""
  azureOpenaiBaseUrl: ""
  azureOpenaiApiKey: ""

arkResources:
  deploy: true

