apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ark-pr-reviewer.fullname" . }}-secrets
  namespace: {{ .Values.config.kubernetesNamespace }}
  labels:
    {{- include "ark-pr-reviewer.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-token: {{ .Values.secrets.githubToken | quote }}
  jira-base-url: {{ .Values.secrets.jiraBaseUrl | quote }}
  jira-username: {{ .Values.secrets.jiraUsername | default "" | quote }}
  jira-api-token: {{ .Values.secrets.jiraApiToken | default "" | quote }}
  azure-openai-base-url: {{ .Values.secrets.azureOpenaiBaseUrl | quote }}
  azure-openai-api-key: {{ .Values.secrets.azureOpenaiApiKey | quote }}

